export const BLOG_POSTS = [
  {
    id: 'spring-2025-eyewear-trends',
    slug: 'spring-2025-eyewear-trends',
    title: '5 tendances lunettes qui définissent le printemps 2025',
    excerpt: 'Des silhouettes oversize aux métaux rétro-futuristes, voici les styles de montures qui dominent les podiums et les rues cette saison.',
    category: 'Tendances',
    readTime: '4 min de lecture',
    date: '15 mars 2025',
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800',
    author: { name: 'Sara Alami', role: 'Directrice de style' },
    featured: true,
    tags: ['tendances', 'printemps', 'style'],
  },
  {
    id: 'progressive-lenses-guide',
    slug: 'progressive-lenses-complete-guide',
    title: 'Verres progressifs : le guide complet pour les débutants',
    excerpt: 'Tout ce que vous devez savoir avant de passer aux progressifs — durée d\'adaptation, zones de vision et choix de la bonne monture.',
    category: 'Éducation',
    readTime: '7 min de lecture',
    date: '28 février 2025',
    image: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800',
    author: { name: 'Dr. Mohamed Tahir', role: 'Spécialiste optique' },
    featured: true,
    tags: ['verres', 'progressifs', 'guide'],
  },
  {
    id: 'titanium-vs-acetate',
    slug: 'titanium-vs-acetate-frames',
    title: 'Titane vs Acétate : quelle matière de monture vous convient ?',
    excerpt: 'Avantages, inconvénients, poids, durabilité et prix des deux matériaux de montures les plus populaires du marché.',
    category: 'Éducation',
    readTime: '5 min de lecture',
    date: '10 février 2025',
    image: 'https://images.unsplash.com/photo-1509695507497-903c140c43b0?w=800',
    author: { name: 'Karim Benali', role: 'Designer produit' },
    featured: false,
    tags: ['matériaux', 'titane', 'acétate'],
  },
  {
    id: 'blue-light-glasses-worth-it',
    slug: 'blue-light-glasses-worth-it',
    title: 'Les lunettes anti-lumière bleue valent-elles vraiment le coup ?',
    excerpt: 'Nous avons passé en revue les dernières études scientifiques pour savoir si les verres anti-lumière bleue tiennent leurs promesses.',
    category: 'Santé',
    readTime: '6 min de lecture',
    date: '22 janvier 2025',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800',
    author: { name: 'Dr. Nadia Tahir', role: 'Optométriste' },
    featured: false,
    tags: ['lumière-bleue', 'santé', 'verres', 'science'],
  },
  {
    id: 'salon-optique-2025',
    slug: 'salon-optique-2025-highlights',
    title: 'Salon International de l\'Optique 2025 : nos coups de cœur',
    excerpt: 'Nous avons parcouru chaque allée du salon. Voici les créations marquantes, les marques émergentes et les innovations matériaux qui nous ont le plus enthousiasmés.',
    category: 'Événements',
    readTime: '5 min de lecture',
    date: '15 janvier 2025',
    image: 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=800',
    author: { name: 'Sara Alami', role: 'Directrice de style' },
    featured: false,
    tags: ['événements', 'tendances', 'innovation'],
  },
  {
    id: 'care-for-glasses',
    slug: 'how-to-care-for-your-glasses',
    title: 'Comment entretenir vos lunettes — et les faire durer des années',
    excerpt: 'Nettoyage, rangement, ajustements et ce qu\'il faut éviter. Le guide définitif pour garder vos montures et vos verres en parfait état.',
    category: 'Entretien',
    readTime: '4 min de lecture',
    date: '5 janvier 2025',
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800',
    author: { name: 'Karim Benali', role: 'Designer produit' },
    featured: false,
    tags: ['entretien', 'maintenance', 'conseils'],
  },
];
