import type { Product, LensOption } from './types';

// ─── Shared Lens Options ──────────────────────────────────────────────────────

export const LENS_OPTIONS: LensOption[] = [
  {
    id: 'single-vision',
    name: 'Unifocal',
    description: 'Correction de prescription standard pour la vision de loin ou de près',
    price: 0,
    features: ['Protection UV400', 'Traitement anti-rayures', 'Qualité standard'],
  },
  {
    id: 'progressive',
    name: 'Progressif',
    description: 'Correction continue pour toutes les distances — sans ligne de démarcation',
    price: 120,
    features: ['Sans lignes visibles', 'Loin + intermédiaire + lecture', 'Optique HD'],
  },
  {
    id: 'blue-light',
    name: 'Anti-lumière bleue',
    description: 'Filtre la lumière bleue nocive des écrans',
    price: 50,
    features: ['Réduit la fatigue oculaire numérique', 'Améliore la qualité du sommeil', 'Anti-reflets'],
  },
  {
    id: 'photochromic',
    name: 'Photochromique',
    description: 'S\'assombrit automatiquement en plein soleil',
    price: 90,
    features: ['S\'adapte aux conditions lumineuses', 'Protection UV', 'Pas besoin de changer de lunettes'],
  },
  {
    id: 'polarized',
    name: 'Polarisé',
    description: 'Élimine les reflets pour une vision parfaite en extérieur',
    price: 70,
    features: ['Élimination des reflets', 'Contraste amélioré', 'Idéal pour la conduite et l\'extérieur'],
  },
];

// ─── Product Catalog ──────────────────────────────────────────────────────────

export const PRODUCTS: Product[] = [

  // ── Wooby Eyewear — Real Products ──────────────────────────────────────────
  {
    id: 'wooby-w4962s-c1',
    slug: 'cosmos-gold-w4962s-c1',
    name: 'Cosmos Gold',
    brand: 'Wooby Eyewear',
    category: 'sunglasses',
    price: 350,
    compareAtPrice: 480,
    description:
      'Monture métallique dorée avec verres rectangulaires géométriques et double pont. Design contemporain qui allie élégance et modernité. Branches noires décoratives avec détails gravés. Protection UV400. Fabriqué en Italie.',
    shortDescription: 'Monture géométrique dorée, verres fumés, double pont. UV400.',
    images: [
      '/images/products/W4962S-C1-photo.jpg',
      '/images/products/W4962S-C1-model1.jpg',
    ],
    tryOnImage: '/images/products/W4962S-C1-tryon.png',
    frameShape: 'geometric',
    frameType: 'full-rim',
    material: 'metal',
    gender: 'unisex',
    colors: [
      { name: 'Or / Fumé', hex: '#C8A028', frameHex: '#C8A028', lensHex: '#1a1a22' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'heart'],
    tags: ['wooby', 'or', 'géométrique', 'soleil', 'double-pont', 'uv400'],
    stock: 20,
    sku: 'W4962S-C1',
    rating: 4.9,
    reviewCount: 18,
    featured: true,
    bestSeller: true,
    newArrival: true,
    onSale: true,
    salePercentage: 27,
    specifications: {
      'Forme': 'Géométrique / Octogonal',
      'Matière monture': 'Métal doré',
      'Matière verres': 'Polycarbonate',
      'Protection': 'UV400',
      'Pont': 'Double pont',
      'Marque': 'Wooby Eyewear',
      'Origine': 'Italie',
    },
    createdAt: '2025-01-10T10:00:00Z',
  },

  // ── Demo / Placeholder Products ─────────────────────────────────────────────
  {
    id: 'co-001',
    slug: 'navigator-classic-black',
    name: 'Navigator Classic',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 189,
    compareAtPrice: 240,
    description:
      'La Navigator Classic est une monture carrée intemporelle taillée dans un acétate italien premium. Sa silhouette affirmée convient aux traits forts tout en restant légère pour un confort toute la journée. Inspirée du design optique du milieu du siècle, cette monture allie savoir-faire traditionnel et précision moderne.',
    shortDescription: 'Monture carrée intemporelle en acétate italien premium.',
    images: [
      'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800',
      'https://images.unsplash.com/photo-1509695507497-903c140c43b0?w=800',
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800',
    ],
    modelFile: '/models/navigator-classic.glb',
    frameShape: 'square',
    frameType: 'full-rim',
    material: 'acetate',
    gender: 'unisex',
    colors: [
      { name: 'Matte Black', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#2d3748' },
      { name: 'Tortoise', hex: '#8B4513', frameHex: '#8B4513', lensHex: '#c09060' },
      { name: 'Crystal Brown', hex: '#6B3A2A', frameHex: '#6B3A2A', lensHex: '#d4a574' },
      { name: 'Navy Blue', hex: '#1a237e', frameHex: '#1a237e', lensHex: '#3949ab' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'heart'],
    tags: ['classic', 'square', 'acetate', 'bestseller'],
    stock: 24,
    sku: 'CO-NAV-001-BLK',
    rating: 4.8,
    reviewCount: 127,
    featured: true,
    bestSeller: true,
    newArrival: false,
    onSale: true,
    salePercentage: 21,
    specifications: {
      'Lens Width': '52mm',
      'Bridge Width': '18mm',
      'Temple Length': '145mm',
      'Frame Weight': '22g',
      'Material': 'Premium Italian Acetate',
      'Lens Material': 'Polycarbonate',
    },
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'co-002',
    slug: 'lumiere-round-gold',
    name: 'Lumière Round',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 215,
    description:
      'Délicate mais impactante, la Lumière Round propose des montures en titane ultra-fines avec une lentille parfaitement circulaire. Inspirée du style raffiné des grandes villes, elle allie sophistication et légèreté incomparable. Les détails du pont doré ajoutent une touche de luxe.',
    shortDescription: 'Montures rondes ultra-fines en titane avec accents dorés.',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800',
      'https://images.unsplash.com/photo-1576558656222-ba66febe3dec?w=800',
    ],
    modelFile: '/models/lumiere-round.glb',
    frameShape: 'round',
    frameType: 'full-rim',
    material: 'titanium',
    gender: 'unisex',
    colors: [
      { name: 'Gold', hex: '#C9A84C', frameHex: '#C9A84C', lensHex: '#e8d5a3' },
      { name: 'Silver', hex: '#C0C0C0', frameHex: '#C0C0C0', lensHex: '#e8e8e8' },
      { name: 'Rose Gold', hex: '#E8A598', frameHex: '#E8A598', lensHex: '#f5d5c8' },
      { name: 'Gunmetal', hex: '#4a4a4a', frameHex: '#4a4a4a', lensHex: '#888888' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['square', 'diamond', 'oblong'],
    tags: ['round', 'titanium', 'lightweight', 'luxury'],
    stock: 18,
    sku: 'CO-LUM-002-GLD',
    rating: 4.9,
    reviewCount: 89,
    featured: true,
    bestSeller: true,
    newArrival: false,
    onSale: false,
    specifications: {
      'Lens Width': '46mm',
      'Bridge Width': '20mm',
      'Temple Length': '140mm',
      'Frame Weight': '12g',
      'Material': 'Grade-5 Titanium',
      'Lens Material': 'Mineral Glass',
    },
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'co-003',
    slug: 'eclipse-cat-eye-tortoise',
    name: 'Eclipse Cat-Eye',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 199,
    compareAtPrice: 250,
    description:
      'L\'Eclipse Cat-Eye est une monture audacieuse et féminine qui réinterprète le glamour des années 1960 dans une silhouette moderne. Les coins relevés et les angles dramatiques en font une pièce de caractère pour toute garde-robe. Fabriquée à la main en Italie en acétate luxueux.',
    shortDescription: 'Monture papillon audacieuse des années 1960 en acétate italien.',
    images: [
      'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800',
      'https://images.unsplash.com/photo-1483401757487-2ced3fa77952?w=800',
    ],
    modelFile: '/models/eclipse-cat-eye.glb',
    frameShape: 'cat-eye',
    frameType: 'full-rim',
    material: 'acetate',
    gender: 'women',
    colors: [
      { name: 'Tortoise', hex: '#8B4513', frameHex: '#8B4513', lensHex: '#c09060' },
      { name: 'Black Pearl', hex: '#1a1a2e', frameHex: '#1a1a2e', lensHex: '#4a4a6a' },
      { name: 'Berry', hex: '#8e2157', frameHex: '#8e2157', lensHex: '#c06090' },
      { name: 'Champagne', hex: '#d4a96a', frameHex: '#d4a96a', lensHex: '#e8c890' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'square'],
    tags: ['cat-eye', 'women', 'bold', 'vintage'],
    stock: 15,
    sku: 'CO-ECL-003-TORT',
    rating: 4.7,
    reviewCount: 64,
    featured: true,
    bestSeller: false,
    newArrival: true,
    onSale: true,
    salePercentage: 20,
    specifications: {
      'Lens Width': '54mm',
      'Bridge Width': '17mm',
      'Temple Length': '142mm',
      'Frame Weight': '26g',
      'Material': 'Premium Italian Acetate',
      'Lens Material': 'Polycarbonate',
    },
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'co-004',
    slug: 'aviator-pro-silver',
    name: 'Aviator Pro',
    brand: 'Clic Optique',
    category: 'sunglasses',
    price: 249,
    description:
      'Une réinterprétation moderne de la silhouette aviateur classique. L\'Aviator Pro propose des montures ultra-légères en acier inoxydable avec des verres polarisés offrant une clarté incomparable. Parfaite pour les aventures en plein air ou la vie en ville.',
    shortDescription: 'Lunettes de soleil aviateur modernes avec verres polarisés.',
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800',
      'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800',
    ],
    modelFile: '/models/aviator-pro.glb',
    frameShape: 'aviator',
    frameType: 'semi-rim',
    material: 'metal',
    gender: 'unisex',
    colors: [
      { name: 'Silver/Grey', hex: '#C0C0C0', frameHex: '#C0C0C0', lensHex: '#607080' },
      { name: 'Gold/Brown', hex: '#C9A84C', frameHex: '#C9A84C', lensHex: '#8B6914' },
      { name: 'Gunmetal/Green', hex: '#4a4a4a', frameHex: '#4a4a4a', lensHex: '#2d5a27' },
      { name: 'Rose Gold/Pink', hex: '#E8A598', frameHex: '#E8A598', lensHex: '#c0607a' },
    ],
    lensOptions: [LENS_OPTIONS[0], LENS_OPTIONS[4]],
    faceShapeRecommendation: ['oval', 'square', 'diamond'],
    tags: ['aviator', 'sunglasses', 'polarized', 'classic'],
    stock: 32,
    sku: 'CO-AVI-004-SLV',
    rating: 4.9,
    reviewCount: 203,
    featured: true,
    bestSeller: true,
    newArrival: false,
    onSale: false,
    specifications: {
      'Lens Width': '58mm',
      'Bridge Width': '14mm',
      'Temple Length': '148mm',
      'Frame Weight': '20g',
      'Material': 'Stainless Steel',
      'Lens Material': 'Polarized Mineral Glass',
    },
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'co-005',
    slug: 'nordic-rectangle-navy',
    name: 'Nordic Rectangle',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 175,
    description:
      'Le design minimaliste scandinave rencontre la précision optique. La Nordic Rectangle propose des branches ultra-fines en titane et une façade légère en TR-90 pour un confort toute la journée. Lignes épurées, sans fioritures.',
    shortDescription: 'Montures rectangulaires minimalistes d\'inspiration scandinave.',
    images: [
      'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800',
      'https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?w=800',
    ],
    modelFile: '/models/nordic-rectangle.glb',
    frameShape: 'rectangle',
    frameType: 'full-rim',
    material: 'tr-90',
    gender: 'men',
    colors: [
      { name: 'Navy Blue', hex: '#1a237e', frameHex: '#1a237e', lensHex: '#3949ab' },
      { name: 'Matte Black', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#2d3748' },
      { name: 'Forest Green', hex: '#1b5e20', frameHex: '#1b5e20', lensHex: '#388e3c' },
      { name: 'Burgundy', hex: '#6a0032', frameHex: '#6a0032', lensHex: '#c62828' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'heart'],
    tags: ['rectangle', 'minimal', 'men', 'lightweight'],
    stock: 28,
    sku: 'CO-NOR-005-NVY',
    rating: 4.6,
    reviewCount: 91,
    featured: false,
    bestSeller: true,
    newArrival: false,
    onSale: false,
    specifications: {
      'Lens Width': '53mm',
      'Bridge Width': '17mm',
      'Temple Length': '143mm',
      'Frame Weight': '16g',
      'Material': 'TR-90 + Titanium temples',
      'Lens Material': 'Polycarbonate',
    },
    createdAt: '2024-02-15T10:00:00Z',
  },
  {
    id: 'co-006',
    slug: 'tropicana-oversized-black',
    name: 'Tropicana Oversized',
    brand: 'Clic Optique',
    category: 'sunglasses',
    price: 229,
    compareAtPrice: 280,
    description:
      'Affirmez votre style où que vous alliez. Les lunettes de soleil Tropicana Oversized arborent de larges verres carrés et des montures épaisses en acétate pour un impact mode maximal. La protection UV400 protège vos yeux avec élégance.',
    shortDescription: 'Lunettes de soleil oversize carrées et audacieuses en acétate épais.',
    images: [
      'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=800',
      'https://images.unsplash.com/photo-1501117716987-c8c394bb29df?w=800',
    ],
    modelFile: '/models/tropicana-oversized.glb',
    frameShape: 'square',
    frameType: 'full-rim',
    material: 'acetate',
    gender: 'women',
    colors: [
      { name: 'Jet Black', hex: '#000000', frameHex: '#000000', lensHex: '#1a1a1a' },
      { name: 'White Pearl', hex: '#F5F5F5', frameHex: '#F5F5F5', lensHex: '#d0d0d0' },
      { name: 'Caramel', hex: '#C68642', frameHex: '#C68642', lensHex: '#8B6914' },
      { name: 'Coral', hex: '#FF6B6B', frameHex: '#FF6B6B', lensHex: '#e84040' },
    ],
    lensOptions: [LENS_OPTIONS[0], LENS_OPTIONS[4]],
    faceShapeRecommendation: ['oval', 'oblong', 'diamond'],
    tags: ['oversized', 'sunglasses', 'fashion', 'women'],
    stock: 19,
    sku: 'CO-TRO-006-BLK',
    rating: 4.7,
    reviewCount: 76,
    featured: false,
    bestSeller: false,
    newArrival: true,
    onSale: true,
    salePercentage: 18,
    specifications: {
      'Lens Width': '60mm',
      'Bridge Width': '16mm',
      'Temple Length': '145mm',
      'Frame Weight': '30g',
      'Material': 'Premium Acetate',
      'Lens Material': 'UV400 Polycarbonate',
    },
    createdAt: '2024-03-20T10:00:00Z',
  },
  {
    id: 'co-007',
    slug: 'heritage-browline-gold',
    name: 'Heritage Browline',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 195,
    description:
      'Un hommage au style américain des années 1950, la Heritage Browline combine une barre sourcilière en acétate audacieux avec des bords inférieurs délicats en métal. Cette silhouette iconique convient aussi bien aux intellectuels qu\'aux personnes tendance.',
    shortDescription: 'Monture browline classique des années 1950 avec bord inférieur en métal.',
    images: [
      'https://images.unsplash.com/photo-1529946825340-30f021e56da3?w=800',
    ],
    modelFile: '/models/heritage-browline.glb',
    frameShape: 'browline',
    frameType: 'semi-rim',
    material: 'mixed',
    gender: 'men',
    colors: [
      { name: 'Black/Gold', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#C9A84C' },
      { name: 'Tortoise/Gold', hex: '#8B4513', frameHex: '#8B4513', lensHex: '#C9A84C' },
      { name: 'Navy/Silver', hex: '#1a237e', frameHex: '#1a237e', lensHex: '#C0C0C0' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'oblong'],
    tags: ['browline', 'vintage', 'men', 'classic'],
    stock: 12,
    sku: 'CO-HER-007-GLD',
    rating: 4.8,
    reviewCount: 55,
    featured: false,
    bestSeller: false,
    newArrival: false,
    onSale: false,
    specifications: {
      'Lens Width': '50mm',
      'Bridge Width': '19mm',
      'Temple Length': '145mm',
      'Frame Weight': '24g',
      'Material': 'Acetate + Stainless Steel',
      'Lens Material': 'Polycarbonate',
    },
    createdAt: '2024-01-30T10:00:00Z',
  },
  {
    id: 'co-008',
    slug: 'aero-sport-wrap',
    name: 'Aero Sport Wrap',
    brand: 'Clic Optique',
    category: 'sports',
    price: 169,
    description:
      'Conçue pour la performance. L\'Aero Sport Wrap propose un design enveloppant aérodynamique avec des montures flexibles en TR-90 et des verres polarisés interchangeables. Faite pour les athlètes, idéale pour tous.',
    shortDescription: 'Lunettes de sport enveloppantes aérodynamiques avec verres interchangeables.',
    images: [
      'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800',
    ],
    modelFile: '/models/aero-sport.glb',
    frameShape: 'geometric',
    frameType: 'full-rim',
    material: 'tr-90',
    gender: 'unisex',
    colors: [
      { name: 'Matte Black/Red', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#c62828' },
      { name: 'White/Blue', hex: '#f5f5f5', frameHex: '#f5f5f5', lensHex: '#1565c0' },
      { name: 'Carbon/Green', hex: '#37474f', frameHex: '#37474f', lensHex: '#2e7d32' },
    ],
    lensOptions: [LENS_OPTIONS[0], LENS_OPTIONS[4]],
    faceShapeRecommendation: ['oval', 'square', 'oblong'],
    tags: ['sport', 'polarized', 'lightweight', 'outdoor'],
    stock: 35,
    sku: 'CO-AER-008-BLK',
    rating: 4.5,
    reviewCount: 142,
    featured: false,
    bestSeller: false,
    newArrival: false,
    onSale: false,
    specifications: {
      'Lens Width': '65mm',
      'Bridge Width': '12mm',
      'Temple Length': '120mm',
      'Frame Weight': '28g',
      'Material': 'TR-90 Nylon',
      'Lens Material': 'Polarized Polycarbonate',
    },
    createdAt: '2024-02-05T10:00:00Z',
  },

  // ── New Arrivals & Additions ─────────────────────────────────────────────────

  {
    id: 'co-009',
    slug: 'manhattan-square-gold',
    name: 'Manhattan Square',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 189,
    compareAtPrice: undefined,
    description:
      'Inspirée de l\'architecture géométrique des grandes métropoles, la Manhattan Square combine des proportions audacieuses avec des détails dorés raffinés. Les branches en acétate artisanales s\'associent à une façade en métal légère pour une esthétique urbaine moderne.',
    shortDescription: 'Montures géométriques audacieuses avec détails dorés pour un look citadin.',
    images: [
      'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=800',
      'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=800',
    ],
    frameShape: 'square',
    frameType: 'full-rim',
    material: 'mixed',
    gender: 'unisex',
    colors: [
      { name: 'Gold/Tortoise', hex: '#C9A84C', frameHex: '#C9A84C', lensHex: '#8B6914' },
      { name: 'Silver/Black', hex: '#9E9E9E', frameHex: '#9E9E9E', lensHex: '#212121' },
      { name: 'Rose Gold/Clear', hex: '#E8A598', frameHex: '#E8A598', lensHex: '#E0E0E0' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'heart'],
    tags: ['urban', 'geometric', 'gold', 'premium'],
    stock: 22,
    sku: 'CO-MAN-009-GLD',
    rating: 4.7,
    reviewCount: 68,
    featured: true,
    bestSeller: false,
    newArrival: true,
    onSale: false,
    specifications: {
      'Lens Width': '52mm',
      'Bridge': '18mm',
      'Temple Length': '145mm',
      'Frame Weight': '19g',
      'Material': 'Acetate/Metal',
    },
  },

  {
    id: 'co-010',
    slug: 'riviera-rimless-silver',
    name: 'Riviera Rimless',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 229,
    compareAtPrice: undefined,
    description:
      'La Riviera Rimless représente le summum du luxe invisible. Des montures per-drill ultra-fines maintiennent des verres cristallins avec pratiquement aucune monture visible, laissant vos traits naturels s\'exprimer. D\'une légèreté extrême à seulement 12g.',
    shortDescription: 'Design sans cercle ultra-minimaliste — quasiment invisible sur le visage.',
    images: [
      'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800',
      'https://images.unsplash.com/photo-1509695507497-903c140c43b0?w=800',
    ],
    frameShape: 'rectangle',
    frameType: 'rimless',
    material: 'titanium',
    gender: 'unisex',
    colors: [
      { name: 'Silver', hex: '#C0C0C0', frameHex: '#C0C0C0', lensHex: '#E8E8E8' },
      { name: 'Gold', hex: '#C9A84C', frameHex: '#C9A84C', lensHex: '#F5F0E0' },
      { name: 'Gunmetal', hex: '#4A4A4A', frameHex: '#4A4A4A', lensHex: '#D0D0D0' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'square', 'oblong', 'diamond'],
    tags: ['rimless', 'minimalist', 'titanium', 'luxury', 'lightweight'],
    stock: 15,
    sku: 'CO-RIV-010-SLV',
    rating: 4.9,
    reviewCount: 41,
    featured: true,
    bestSeller: false,
    newArrival: true,
    onSale: false,
    specifications: {
      'Lens Width': '54mm',
      'Bridge': '16mm',
      'Temple Length': '140mm',
      'Frame Weight': '12g',
      'Material': 'Titanium',
    },
  },

  {
    id: 'co-011',
    slug: 'havana-round-tortoise',
    name: 'Havana Round',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 159,
    compareAtPrice: 199,
    description:
      'Adoptez le style classique Havana avec ces montures rondes en acétate artisanales. Le riche motif écaille est unique pour chaque paire, taillée dans du bio-acétate italien. Une monture intemporelle qui fait le pont entre rétro et contemporain.',
    shortDescription: 'Montures rondes artisanales en bio-acétate italien aux teintes écaille.',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800',
      'https://images.unsplash.com/photo-1576558656222-ba66febe3dec?w=800',
    ],
    frameShape: 'round',
    frameType: 'full-rim',
    material: 'acetate',
    gender: 'unisex',
    colors: [
      { name: 'Classic Tortoise', hex: '#8B5E3C', frameHex: '#8B5E3C', lensHex: '#C8A882' },
      { name: 'Dark Havana', hex: '#4A2C1A', frameHex: '#4A2C1A', lensHex: '#8B6914' },
      { name: 'Honey', hex: '#D4A853', frameHex: '#D4A853', lensHex: '#E8D5A0' },
      { name: 'Black', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#555555' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['square', 'diamond', 'oblong'],
    tags: ['tortoise', 'round', 'acetate', 'italian', 'retro'],
    stock: 30,
    sku: 'CO-HAV-011-TRT',
    rating: 4.6,
    reviewCount: 93,
    featured: false,
    bestSeller: true,
    newArrival: false,
    onSale: true,
    salePercentage: 20,
    specifications: {
      'Lens Width': '48mm',
      'Bridge': '22mm',
      'Temple Length': '145mm',
      'Frame Weight': '24g',
      'Material': 'Italian Bio-Acetate',
    },
  },

  {
    id: 'co-012',
    slug: 'monaco-cat-eye-gold',
    name: 'Monaco Cat-Eye',
    brand: 'Clic Optique',
    category: 'sunglasses',
    price: 249,
    compareAtPrice: undefined,
    description:
      'Le glamour rencontre la Méditerranée avec la Monaco Cat-Eye. Montures papillon oversize en acétate avec une silhouette dramatiquement relevée, verres dégradés UV400 et rivets dorés polis à la main. À porter avec crème solaire et élégance.',
    shortDescription: 'Lunettes de soleil glamour oversize avec verres dégradés UV400.',
    images: [
      'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800',
      'https://images.unsplash.com/photo-1483401757487-2ced3fa77952?w=800',
    ],
    frameShape: 'cat-eye',
    frameType: 'full-rim',
    material: 'acetate',
    gender: 'women',
    colors: [
      { name: 'Black/Gold', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#2C2C2C' },
      { name: 'Ivory/Gold', hex: '#F5F0E0', frameHex: '#F5F0E0', lensHex: '#A0946A' },
      { name: 'Burgundy', hex: '#6D1F2A', frameHex: '#6D1F2A', lensHex: '#8B2635' },
    ],
    lensOptions: [LENS_OPTIONS[0], LENS_OPTIONS[4]],
    faceShapeRecommendation: ['round', 'square', 'oval', 'heart'],
    tags: ['glamour', 'sunglasses', 'oversized', 'gold', 'feminine'],
    stock: 18,
    sku: 'CO-MON-012-GLD',
    rating: 4.8,
    reviewCount: 57,
    featured: true,
    bestSeller: false,
    newArrival: true,
    onSale: false,
    specifications: {
      'Lens Width': '58mm',
      'Bridge': '16mm',
      'Temple Length': '145mm',
      'Frame Weight': '28g',
      'Material': 'Acetate',
      'Lens': 'UV400 Gradient',
    },
  },

  {
    id: 'co-013',
    slug: 'tokyo-slim-black',
    name: 'Tokyo Slim',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 175,
    compareAtPrice: undefined,
    description:
      'Conçue avec précision dans l\'esprit du minimalisme japonais. La Tokyo Slim propose des branches en titane extrêmement fines, un pont à clé délicat et des verres ultra-étroits. Tout a été épuré pour ne garder que l\'essentiel.',
    shortDescription: 'Montures en titane d\'inspiration japonaise au profil ultra-fin.',
    images: [
      'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800',
      'https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?w=800',
    ],
    frameShape: 'rectangle',
    frameType: 'semi-rimless',
    material: 'titanium',
    gender: 'unisex',
    colors: [
      { name: 'Matte Black', hex: '#212121', frameHex: '#212121', lensHex: '#424242' },
      { name: 'Brushed Silver', hex: '#B0BEC5', frameHex: '#B0BEC5', lensHex: '#D0D8DC' },
      { name: 'Midnight Navy', hex: '#1A237E', frameHex: '#1A237E', lensHex: '#283593' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'heart', 'diamond'],
    tags: ['japanese', 'minimalist', 'titanium', 'slim', 'semi-rimless'],
    stock: 25,
    sku: 'CO-TOK-013-BLK',
    rating: 4.7,
    reviewCount: 49,
    featured: false,
    bestSeller: false,
    newArrival: true,
    onSale: false,
    specifications: {
      'Lens Width': '50mm',
      'Bridge': '19mm',
      'Temple Length': '140mm',
      'Frame Weight': '14g',
      'Material': 'Pure Titanium',
    },
  },

  {
    id: 'co-014',
    slug: 'capri-round-sunglasses',
    name: 'Capri Round',
    brand: 'Clic Optique',
    category: 'sunglasses',
    price: 195,
    compareAtPrice: 219,
    description:
      'L\'élégance estivale méditerranéenne en cercle parfait. La Capri Round propose un pont à clé, des verres teintés plats et une monture en métal fine aux tons dorés chauds. Du bord de mer à votre quotidien.',
    shortDescription: 'Lunettes de soleil rondes classiques avec verres teintés plats et monture métal dorée.',
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800',
      'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800',
    ],
    frameShape: 'round',
    frameType: 'full-rim',
    material: 'metal',
    gender: 'women',
    colors: [
      { name: 'Gold/Green', hex: '#C9A84C', frameHex: '#C9A84C', lensHex: '#558B2F' },
      { name: 'Gold/Brown', hex: '#C9A84C', frameHex: '#C9A84C', lensHex: '#6D4C41' },
      { name: 'Silver/Grey', hex: '#B0BEC5', frameHex: '#B0BEC5', lensHex: '#546E7A' },
      { name: 'Rose Gold/Pink', hex: '#E8A598', frameHex: '#E8A598', lensHex: '#F48FB1' },
    ],
    lensOptions: [LENS_OPTIONS[0], LENS_OPTIONS[4]],
    faceShapeRecommendation: ['square', 'oblong', 'diamond'],
    tags: ['round', 'sunglasses', 'italian', 'summer', 'gold'],
    stock: 40,
    sku: 'CO-CAP-014-GLD',
    rating: 4.5,
    reviewCount: 112,
    featured: false,
    bestSeller: true,
    newArrival: false,
    onSale: true,
    salePercentage: 11,
    specifications: {
      'Lens Width': '49mm',
      'Bridge': '21mm',
      'Temple Length': '145mm',
      'Frame Weight': '20g',
      'Material': 'Metal',
      'Lens': 'UV400 Flat Tint',
    },
  },

  {
    id: 'co-015',
    slug: 'nordic-browline-silver',
    name: 'Nordic Browline II',
    brand: 'Clic Optique',
    category: 'eyeglasses',
    price: 199,
    compareAtPrice: undefined,
    description:
      'Une évolution raffinée de la silhouette browline classique. La Nordic Browline II associe une barre sourcilière supérieure en acétate audacieux à des bords inférieurs ultra-fins en métal, pour un look qui marie l\'héritage des années 1950 à la sobriété scandinave.',
    shortDescription: 'Interprétation contemporaine du browline intemporel en matériaux mixtes.',
    images: [
      'https://images.unsplash.com/photo-1529946825340-30f021e56da3?w=800',
      'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800',
    ],
    frameShape: 'browline',
    frameType: 'semi-rimless',
    material: 'mixed',
    gender: 'men',
    colors: [
      { name: 'Black/Silver', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#C0C0C0' },
      { name: 'Tortoise/Gold', hex: '#8B5E3C', frameHex: '#8B5E3C', lensHex: '#C9A84C' },
      { name: 'Blue/Silver', hex: '#1565C0', frameHex: '#1565C0', lensHex: '#90CAF9' },
    ],
    lensOptions: LENS_OPTIONS,
    faceShapeRecommendation: ['oval', 'round', 'square', 'heart'],
    tags: ['browline', 'mixed', 'heritage', 'semi-rimless'],
    stock: 20,
    sku: 'CO-NOR-015-SLV',
    rating: 4.6,
    reviewCount: 38,
    featured: false,
    bestSeller: false,
    newArrival: true,
    onSale: false,
    specifications: {
      'Lens Width': '51mm',
      'Bridge': '20mm',
      'Temple Length': '145mm',
      'Frame Weight': '21g',
      'Material': 'Acetate/Metal',
    },
  },

  {
    id: 'co-016',
    slug: 'sahara-oversized-sunglasses',
    name: 'Sahara Oversized',
    brand: 'Clic Optique',
    category: 'sunglasses',
    price: 215,
    compareAtPrice: undefined,
    description:
      'Une couverture maximale pour un style désert-chic. La Sahara Oversized propose des montures en acétate sculpturales, une protection UV400 enveloppante et des branches épaisses avec des détails métalliques apparents. Audacieuse, protectrice, inoubliable.',
    shortDescription: 'Lunettes de soleil oversize à fort impact avec protection UV400 totale.',
    images: [
      'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=800',
      'https://images.unsplash.com/photo-1501117716987-c8c394bb29df?w=800',
    ],
    frameShape: 'oversized',
    frameType: 'full-rim',
    material: 'acetate',
    gender: 'unisex',
    colors: [
      { name: 'Sand/Smoke', hex: '#C4A882', frameHex: '#C4A882', lensHex: '#616161' },
      { name: 'Black/Black', hex: '#1a1a1a', frameHex: '#1a1a1a', lensHex: '#212121' },
      { name: 'Olive/Brown', hex: '#556B2F', frameHex: '#556B2F', lensHex: '#795548' },
      { name: 'White/Grey', hex: '#F5F5F5', frameHex: '#F5F5F5', lensHex: '#9E9E9E' },
    ],
    lensOptions: [LENS_OPTIONS[0], LENS_OPTIONS[4]],
    faceShapeRecommendation: ['oval', 'oblong', 'square'],
    tags: ['oversized', 'sunglasses', 'statement', 'summer', 'UV400'],
    stock: 28,
    sku: 'CO-SAH-016-SND',
    rating: 4.4,
    reviewCount: 75,
    featured: false,
    bestSeller: false,
    newArrival: true,
    onSale: false,
    specifications: {
      'Lens Width': '62mm',
      'Bridge': '14mm',
      'Temple Length': '145mm',
      'Frame Weight': '32g',
      'Material': 'Acetate',
      'Lens': 'UV400',
    },
  },
];

// ─── Helper Functions ─────────────────────────────────────────────────────────

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}

export function getBestSellers(): Product[] {
  return PRODUCTS.filter((p) => p.bestSeller);
}

export function getNewArrivals(): Product[] {
  return PRODUCTS.filter((p) => p.newArrival);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) =>
      p.id !== product.id &&
      (p.category === product.category || p.frameShape === product.frameShape)
  ).slice(0, limit);
}

export const BRANDS = [...new Set(PRODUCTS.map((p) => p.brand))];

export const FACE_SHAPE_GUIDES: Record<
  string,
  { description: string; recommended: string[]; avoid: string[] }
> = {
  oval: {
    description: 'Balanced proportions with a slightly wider forehead. Most frames work well.',
    recommended: ['square', 'rectangle', 'wayfarer', 'aviator', 'round'],
    avoid: [],
  },
  round: {
    description: 'Soft curves with similar width and length.',
    recommended: ['square', 'rectangle', 'browline', 'wayfarer'],
    avoid: ['round', 'oval'],
  },
  square: {
    description: 'Strong jaw and wide forehead with angular features.',
    recommended: ['round', 'oval', 'aviator', 'cat-eye'],
    avoid: ['square', 'rectangle'],
  },
  heart: {
    description: 'Wider forehead tapering to a narrow chin.',
    recommended: ['aviator', 'round', 'oval', 'browline'],
    avoid: ['cat-eye'],
  },
  diamond: {
    description: 'Narrow forehead and jaw with wide cheekbones.',
    recommended: ['cat-eye', 'oval', 'browline', 'rimless'],
    avoid: ['narrow'],
  },
  oblong: {
    description: 'Long and narrow face, longer than wide.',
    recommended: ['round', 'square', 'oversized', 'aviator'],
    avoid: ['narrow', 'rectangle'],
  },
};
